"""
Django settings for cpabong2 project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""



from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-08y9o3x$70=2k3hd*&(pkb342+-zu_+lr_b2g&%*5r%xh3lfb-"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'ckeditor',  # django-ckeditor-5가 제공하는 앱
    'ckeditor_uploader',  # 파일 업로드 지원
    'main',
    'aboutbong',
    'Apps',
    'library',
    'django.contrib.humanize',
    'members',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = "cpabong2.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / 'templates'],  # templates 폴더를 설정
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cpabong2.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",  # 개발용 디렉토리만 지정
]
STATIC_ROOT = BASE_DIR / "staticfiles"  # staticfiles 폴더로 지정

CKEDITOR_UPLOAD_PATH = "uploads/"  # 'uploads/'는 MEDIA_ROOT 아래에 생성되는 디렉토리
CKEDITOR_ALLOW_NONIMAGE_FILES = False  # 이미지 외 파일 업로드 여부
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'extraPlugins': 'codesnippet',  # 코드 스니펫 플러그인 추가
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline', '-', 'CodeSnippet', '-', 'FontSize', 'TextColor', 'BGColor', '-', 'Source'],
            ['Link', 'Unlink'],
            ['NumberedList', 'BulletedList'],
            ['Outdent', 'Indent'],
            ['Blockquote'],
            ['Undo', 'Redo'],
            ['RemoveFormat', 'Maximize'],
        ],
        'extraAllowedContent': 'span[*]{*}(*);',  # 커스텀 스타일 허용
        'fontSize_sizes': '8/8px;10/10px;12/12px;14/14px;16/16px;18/18px;20/20px;24/24px;28/28px;',  # 폰트 크기 옵션
        'height': 400,
        'width': 'auto',
    }
}



# CKEDITOR_5_CONFIGS = {
#     "default": {
#         "toolbar": [
#             "heading",
#             "|",
#             "bold",
#             "italic",
#             "link",
#             "bulletedList",
#             "numberedList",
#             "blockQuote",
#             "codeBlock",
#             "|",
#             "imageUpload",
#             "mediaEmbed",
#             "undo",
#             "redo",
#         ],
#         "image": {"toolbar": ["imageTextAlternative", "imageStyle:full", "imageStyle:side"]},
#     },
# }