# Generated by Django 4.2.16 on 2024-12-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="sjlight_submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("netasset", models.IntegerField()),
                ("netprofit1", models.IntegerField()),
                ("netprofit2", models.IntegerField()),
                ("netprofit3", models.IntegerField()),
                ("stocknum", models.IntegerField()),
                ("val_method", models.CharField(max_length=20)),
                ("val_bigholder", models.CharField(max_length=20)),
            ],
        ),
    ]
